### ISSUE TITLE
local_prefilter::make_pattern_bounds produces invalid values for some special values.

### ISSUE THREAD

**Issue by marehr** [eaasna/valik#38]
I think this is probably a misconfiguration on my side, since I set pattern_size == window_size. It seems I need to set pattern_size >= window_size + 2 (why?).

```
start local_prefilter()
local_prefilter::seq: ACGTAAGTCA
local_prefilter::minimiser: [(63,0),(8,3)]
local_prefilter::window_span_begin: [0,3]
local_prefilter::window_span_end: [7,9]
local_prefilter::make_pattern_bounds::*std::lower_bound(..., begin [= 0]) = 0
local_prefilter::make_pattern_bounds::*std::upper_bound(..., begin + arguments.pattern_size - 1 [= 5]) = 7
local_prefilter::make_pattern_bounds::pattern.first_index = 0
local_prefilter::make_pattern_bounds::pattern.last_index = 18446744073709551615
local_prefilter::make_pattern_bounds::minimiser_count = 0
```

The problem here is that we use "indices" and we can't represent an empty interval with them. A solution would be to change `first_index` (inclusive) and `last_index` (inclusive) to `begin_position` (inclusive) and `end_position` (exclusive).

**Comment by eaasna** [comment]
`--pattern_size` is what you call `--minLength` in stellar.

pattern_size==window_size is a misconfiguration because  there would then only be one k-mer per pattern and the k-mer lemma threshold calculation wouldn't make sense at that point. But there's also the issue that edge cases haven't been taken care of in the app.

I'll create API tests for `make_pattern_bounds` to get a picture of all the edge cases.
